### ISSUE TITLE
Release overview (v0.4.0)

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-portal#153]
### Highlights

- Separation of Profiles App from the rest of the browser

#### Tasks
- [x] https://github.com/blockstack/blockstack-browser/issues/139: Self-hosted S3 doesn't work
- [x] https://github.com/blockstack/blockstack-browser/issues/143: Photo upload support for Blockstack-provided hosting
- [x] https://github.com/blockstack/blockstack-browser/issues/227: create a new contribution markdown file and add toc to readme.md
- [x] https://github.com/blockstack/blockstack-browser/issues/224: iterate the design of the portal dashboard
- [x] https://github.com/blockstack/blockstack-browser/issues/225: ui build of the latest iteration of the portal dashboard design
- [x] https://github.com/blockstack/blockstack-browser/issues/208: Hitting browser quota for redux storage
- [x] https://github.com/blockstack/blockstack-browser/issues/142: Create official dropbox app & add branding
- [x] https://github.com/blockstack/blockstack-browser/issues/123: External web font dependencies break apps
- [x] https://github.com/blockstack/blockstack-browser/issues/231: add the ability for the user to restore an account in the welcome modal
- [x] https://github.com/blockstack/blockstack-browser/issues/134: Gulp dev uses large amount of CPU time
- [x] https://github.com/blockstack/blockstack-browser/issues/168: Display unconfirmed bitcoin wallet balance
- [x] https://github.com/blockstack/blockstack-browser/issues/210: Improve registration prompts
- [x] https://github.com/blockstack/blockstack-browser/issues/230: create a ProfilesApp object that wraps all pages
- [x] https://github.com/blockstack/blockstack-browser/issues/171: Make utxo, transaction broadcast, balance service URLs configurable
- [x] https://github.com/blockstack/blockstack-browser/issues/137: Make 3rd party urls customizable
- [x] https://github.com/blockstack/blockstack-browser/issues/215: Local identities aren't synced with remote identities
- [x] https://github.com/blockstack/blockstack-browser/issues/223: live design of auth view
- [x] https://github.com/blockstack/blockstack-browser/issues/209: Display errors from blockstack-core registration call
- [x] https://github.com/blockstack/blockstack-portal/issues/252: add new "home" logo on all pages of Profile App
- [x] https://github.com/blockstack/blockstack-portal/issues/241: add a wallet app and put the deposit and withdraw pages inside
- [x] https://github.com/blockstack/blockstack-portal/issues/236: hello blockstack ui build
- [x] https://github.com/blockstack/blockstack-portal/issues/240: Mac: Install OS level URI handler
- [x] https://github.com/blockstack/blockstack-portal/issues/235: design hello blockstack app to be consistent with brand

#### Bugs
- [x] https://github.com/blockstack/blockstack-browser/issues/166: Restore account doesn't work
- [x] https://github.com/blockstack/blockstack-browser/issues/192: resolve looping hover transition on profiles search bar
- [x] https://github.com/blockstack/blockstack-portal/issues/244: apps not breaking on dashboard mobile & tablet view

#### Pushed to [Release v0.5.0](https://github.com/blockstack/blockstack-portal/issues/205)
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/202: Add a "home" logo linking to "/profiles" to all pages in the Profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/258: live design new profiles app register pages~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/242: design the wallet app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/220: update ui of profile card in profile app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/136: Explore Permission Types~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/214: design launch modal~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/243: live design a support button~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/218: publish a new blockstack.js library with auth and profiles~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/216: update the auth page to pass auth tokens from core to the app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/219: work with Jude to iron out the authentication requirements~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/251: update the auth page to sign tokens and pass them back to the relying app~~

**Comment by guylepage3** [comment]
closing issue
