### ISSUE TITLE
Release overview (v0.3.0)

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-portal#154]
### Highlights

- The API calls for managing names are being replaced with Blockstack Core
- The new version of the profiles app is being released with a new UI
- The on-boarding process is being improved and reworked

#### Tasks
- [x] https://github.com/blockstack/blockstack-browser/issues/147: apply latest blockstack browser icon set
- [x] https://github.com/blockstack/blockstack-browser/issues/126: Update proofs library to version 0.3.0
- [x] https://github.com/blockstack/blockstack-browser/issues/127: Support Blockstack ID in any namespace
- [x] https://github.com/blockstack/blockstack-browser/issues/125: Git dependencies should use https not git+ssh
- [x] https://github.com/blockstack/blockstack-browser/issues/114: blockstack desktop app product design plan
- [x] https://github.com/blockstack/blockstack-browser/issues/140: design new home screen view
- [x] https://github.com/blockstack/blockstack-browser/issues/155: design new browser portal profiles landing view
- [x] https://github.com/blockstack/blockstack-browser/issues/165: add new reactroot classname for profiles app
- [x] https://github.com/blockstack/blockstack-browser/issues/175: add custom spacing classes to profiles app
- [x] https://github.com/blockstack/blockstack-browser/issues/177: new profiles app style sheet
- [x] https://github.com/blockstack/blockstack-browser/issues/180: create new register button for the profiles app landing view
- [x] https://github.com/blockstack/blockstack-browser/issues/95: require users to input their own blockstack API keys when they set up the browser
- [x] https://github.com/blockstack/blockstack-browser/issues/96: update the way the profile token file URL is supplied to item registration
- [x] https://github.com/blockstack/blockstack-browser/issues/193: build out responsive profile cards in column list on tablet view
- [x] https://github.com/blockstack/blockstack-browser/issues/149: issue building mac app
- [x] https://github.com/blockstack/blockstack-browser/issues/181: apply new design to personas in profile app landing view
- [x] https://github.com/blockstack/blockstack-browser/issues/163: build of new navbar for mobile on profiles landing view
- [x] https://github.com/blockstack/blockstack-browser/issues/111: global replacement of beta to alpha
- [x] https://github.com/blockstack/blockstack-browser/issues/129: Add Bitcoin wallet support
- [x] https://github.com/blockstack/blockstack-browser/issues/160: macOS: Distribute Blockstack with each browser
- [x] https://github.com/blockstack/blockstack-browser/issues/159: Mock blockstack core API
- [x] https://github.com/blockstack/blockstack-browser/issues/162: restructure layout of profiles landing view for all views
- [x] https://github.com/blockstack/blockstack-browser/issues/156: build new browser portal profiles landing view
- [x] https://github.com/blockstack/blockstack-browser/issues/98: Re-enable validation of profile tokens (and integrate the new elliptic curve library to do so)
- [x] https://github.com/blockstack/blockstack-browser/issues/157: blockstack browser portal profile design
- [x] https://github.com/blockstack/blockstack-browser/issues/207: ui build of new profile card in profile app
- [x] https://github.com/blockstack/blockstack-browser/issues/188: integrate the user onboarding screens
- [x] https://github.com/blockstack/blockstack-browser/issues/187: finalize the blockstack core installation process in the mac build
- [x] https://github.com/blockstack/blockstack-browser/issues/186: Start blockstack REST API when Mac App is run
- [x] https://github.com/blockstack/blockstack-browser/issues/158: Integrate the API calls with the Blockstack core REST API
- [x] https://github.com/blockstack/blockstack-browser/issues/146: CORS proxy breaks account registration
- [x] https://github.com/blockstack/blockstack-browser/issues/221: apply latest blockstack branding to settings app
- [x] https://github.com/blockstack/blockstack-browser/issues/184: create the mac build for release v0.3

#### Bugs
- [x] https://github.com/blockstack/blockstack-browser/issues/107: No response on create account
- [x] https://github.com/blockstack/blockstack-browser/issues/164: bug: resolve viewport meta tag issue
- [x] https://github.com/blockstack/blockstack-browser/issues/178: bug: issue targeting magnifying glass btn in profiles search input
- [x] https://github.com/blockstack/blockstack-browser/issues/182: bug: resolve long username display on small @media displays
- [x] https://github.com/blockstack/blockstack-browser/issues/109: Error messages break page style
- [x] https://github.com/blockstack/blockstack-browser/issues/190: resolve scrolling issue on profiles app landing mobile view
- [x] https://github.com/blockstack/blockstack-browser/issues/195: resolve register button wrapping with profiles in profiles app
- [x] https://github.com/blockstack/blockstack-browser/issues/145: A dependency's dependency requires GitHub account
- [x] https://github.com/blockstack/blockstack-browser/issues/194: extend width of profile landing view cards on mobile
- [x] https://github.com/blockstack/blockstack-browser/issues/196: resolve md-lg breaking issues on profiles app
- [x] https://github.com/blockstack/blockstack-browser/issues/138: Resolve error text is white on white background
- [x] https://github.com/blockstack/blockstack-browser/issues/200: npm install fail on web-0.3 branch
- [x] https://github.com/blockstack/blockstack-browser/issues/203: Resolve input field border issues
- [x] https://github.com/blockstack/blockstack-browser/issues/201: Fix spacing issue on profile editing page
- [x] https://github.com/blockstack/blockstack-browser/issues/213: fix spacing issues on settings app
- [x] https://github.com/blockstack/blockstack-browser/issues/185: User acceptance test the Blockstack Core API to prepare for the integration

#### Issues not complete
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/198: create a profile pending view~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/202: Add a "home" logo linking to "/profiles" to all pages in the Profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/206: write issue creation / project management process~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/209: Display errors from blockstack-core registration call~~
- [ ] ~~https://github.com/blockstack/blockstack-browser/issues/210: Improve registration prompts~~

**Comment by guylepage3** [comment]
Whoot! Closing this out.. Great work team!
