### ISSUE TITLE
Release overview (v0.5.0)

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-portal#205]
### Highlights

- n/a

#### Tasks
- [x] https://github.com/blockstack/blockstack-browser/issues/218: publish a new blockstack.js library with auth and profiles
- [x] https://github.com/blockstack/blockstack-portal/issues/251: update the auth page to sign tokens and pass them back to the relying app
- [x] https://github.com/blockstack/blockstack-portal/issues/273: live design edit profile pages
- [x] https://github.com/blockstack/blockstack-portal/issues/294: create new edit profile header component
- [x] https://github.com/blockstack/blockstack-portal/issues/311: macOS: update protocol handler parsing
- [x] https://github.com/blockstack/blockstack-portal/issues/315: Create a blockstack ruby gem to verify authentication responses
- [x] https://github.com/blockstack/blockstack-portal/issues/282: redesign the wallet app icon
- [x] https://github.com/blockstack/blockstack-portal/issues/285: Update the forum to receive and verify auth responses and either log the user in or create an account for the user
- [x] https://github.com/blockstack/blockstack-portal/issues/301: create a quick sign up page for users that don't have a Blockstack account
- [x] https://github.com/blockstack/blockstack-portal/issues/295: Add menu options to macOS app to go directly to Profiles, Wallet & Account.
- [x] https://github.com/blockstack/blockstack-portal/issues/287: Chore: clean up the routes and paths for the pages
- [x] https://github.com/blockstack/blockstack-portal/issues/274: blockstack-js dependency causes npm install to fail without github ssh credentials
- [x] https://github.com/blockstack/blockstack-portal/issues/310: Add ES256K support to ruby-jwt
- [x] https://github.com/blockstack/blockstack-portal/issues/297: add a storage app to the dashboard
- [x] https://github.com/blockstack/blockstack-portal/issues/304: create a download page for the portal
- [x] https://github.com/blockstack/blockstack-portal/issues/277: Proxy-fetch should use a domain whitelist
- [x] https://github.com/blockstack/blockstack-portal/issues/291: Upgrade Blockstack Auth to support username verification
- [x] https://github.com/blockstack/blockstack-portal/issues/305: Core Wallet password not being generated
- [x] https://github.com/blockstack/blockstack-portal/issues/300: design storage app icon
- [x] https://github.com/blockstack/blockstack-portal/issues/283: Update the forum to sign and dispatch auth requests
- [x] https://github.com/blockstack/blockstack-portal/issues/318: add home button to storage app
- [x] https://github.com/blockstack/blockstack-portal/issues/272: design return to home screen & app home standards
- [x] https://github.com/blockstack/blockstack-portal/issues/250: create an overlay that displays the PGP key in the app itself
- [x] https://github.com/blockstack/blockstack-portal/issues/276: Create a plugin that enables blockstack auth for discourse
- [x] https://github.com/blockstack/blockstack-browser/issues/202: adjust layout of profiles app list view (post profiles app object)
- [x] https://github.com/blockstack/blockstack-portal/issues/279: Update macOS app to include Core 0.14.1
- [x] https://github.com/blockstack/blockstack-portal/issues/278: Update portal to release version of Core 0.14.1
- [x] https://github.com/blockstack/blockstack-portal/issues/286: Update the forum usernames so that usernames created outside of Blockstack Auth have a different suffix (like .id)

#### Bugs
- [x] https://github.com/blockstack/blockstack-portal/issues/270: resolve profiles app home button breakage on tablet and mobile view
- [x] https://github.com/blockstack/blockstack-portal/issues/271: resolve profiles app home button tablet & desktop list view
- [x] https://github.com/blockstack/blockstack-portal/issues/293: 975px width breakage on the profiles list view
- [x] https://github.com/blockstack/blockstack-portal/issues/292: second home button appearing on edit profile view
- [x] https://github.com/blockstack/blockstack-portal/issues/319: resolve home screen app positioning
- [x] https://github.com/blockstack/blockstack-portal/issues/280: Error when approving Hello Blockstack log in request

#### Moved to backlog
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/229: Version APIs & track user url customization~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/219: work with Jude to iron out the authentication requirements~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/290: Upgrade Blockstack Auth to support the passing of the base URL for the user's Blockstack Core node~~

#### Pushed to v0.6.0
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/161: Fix & enable test suite~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/249: Move fetches out of react components~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/288: Chore: update the portal codebase to trim out unnecessary utils replace them with the functions in Blockstack Auth~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/245: Reset API button shouldn't disconnect dropbox~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/296: Move macOS virtualenv core build script to core repo~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/289: Update "Hello, Blockstack" to issue read and write calls to core~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/302: design new storage app~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/322: ui build of storage app design~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/262: ui build of edit profile pages inside the profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/261: design of edit profile pages inside the profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/214: design launch modal~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/242: design the wallet app~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/258: live design new profiles app 
register pages~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/259: design live search query view inside profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/260: ui build of live search query view inside profiles app~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/320: resolve flexbox flow orientation on home screen~~

**Comment by guylepage3** [comment]
closing issue
