### ISSUE TITLE
Release overview (v0.6.0)

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-portal#269]
### Highlights

- Automatic updates
- Ability to transfer Blockstack ID's from onename.com
- Functionality for developers to run tests
- Ability for developers to build a copy of "Hello, Blockstack" with user-stored application state
- Blockstack availability on Linux
- Updated UI on Wallet App
- Updated UI on Storage App
- Updated UI on Profiles App profile card

#### Tasks
- [x] https://github.com/blockstack/blockstack-portal/issues/302: design new storage app
- [x] https://github.com/blockstack/blockstack-portal/issues/322: ui build of storage app design
- [x] https://github.com/blockstack/blockstack-portal/issues/338: 5 second lag upon launching Blockstack
- [x] https://github.com/blockstack/blockstack-portal/issues/340: ui build of the staus bar
- [x] https://github.com/blockstack/blockstack-portal/issues/344: status bar documentation
- [x] https://github.com/blockstack/blockstack-portal/issues/317: upgrade click handler in blockstack auth so it checks for the existence of a protocol handler
- [x] https://github.com/blockstack/blockstack-portal/issues/329: macOS: Research different auto update frameworks
- [x] https://github.com/blockstack/blockstack-portal/issues/242: design the wallet app
- [x] https://github.com/blockstack/blockstack-portal/issues/362: redesign wallet app icon design to match app
- [x] https://github.com/blockstack/blockstack-portal/issues/288: Chore: update the portal codebase to trim out unnecessary utils replace them with the functions in Blockstack Auth
- [x] https://github.com/blockstack/blockstack-portal/issues/364: restructure list-group-item in all sidebars
- [x] https://github.com/blockstack/blockstack-portal/issues/363: apply underline technique from reddit to wallet app sidebar items
- [x] https://github.com/blockstack/blockstack-portal/issues/346: design placeholder app icon
- [x] https://github.com/blockstack/blockstack-portal/issues/350: delete version labels
- [x] https://github.com/blockstack/blockstack-portal/issues/336: Ship macOS app in a signed DMG image
- [x] https://github.com/blockstack/blockstack-portal/issues/342: macOS: Add version number to the option-click menu
- [x] https://github.com/blockstack/blockstack-portal/issues/355: macOS: Integrate sparkle update framework
- [x] https://github.com/blockstack/blockstack-portal/issues/367: Disable uglify
- [x] https://github.com/blockstack/blockstack-portal/issues/345: split up components by adding app directories
- [x] https://github.com/blockstack/blockstack-portal/issues/289: Update "Hello, Blockstack" to issue read and write calls to core
- [x] https://github.com/blockstack/blockstack-portal/issues/351: ui build of the wallet app design
- [x] https://github.com/blockstack/blockstack-portal/issues/335: design forum app icon
- [x] https://github.com/blockstack/blockstack-portal/issues/341: Wallet bitcoin address takes a long time to appear
- [x] https://github.com/blockstack/blockstack-portal/issues/237: Dropbox App: Apply for production
- [x] https://github.com/blockstack/blockstack-portal/issues/358: macOS: Set up production update server
- [x] https://github.com/blockstack/blockstack-portal/issues/343: Redirect new users to the wallet to add funds prior to registering
- [ ] https://github.com/blockstack/blockstack-portal/issues/262: ui build of edit profile pages inside the profiles app
- [ ] https://github.com/blockstack/blockstack-portal/issues/261: design of edit profile pages inside the profiles app
- [ ] https://github.com/blockstack/blockstack-portal/issues/258: live design new profiles app 
register pages
- [ ] https://github.com/blockstack/blockstack-portal/issues/259: design live search query view inside profiles app
- [ ] https://github.com/blockstack/blockstack-portal/issues/260: ui build of live search query view inside profiles app

#### Bugs
- [x] https://github.com/blockstack/blockstack-portal/issues/333: npm run dev doesn't parse api password properly
- [x] https://github.com/blockstack/blockstack-portal/issues/347: Funds sent to wallet in portal don't display
- [x] https://github.com/blockstack/blockstack-portal/issues/245: Reset API button shouldn't disconnect dropbox
- [x] https://github.com/blockstack/blockstack-portal/issues/339: Cannot back out of sign in to create profile
- [x] https://github.com/blockstack/blockstack-portal/issues/249: Move fetches out of react components
- [x] https://github.com/blockstack/blockstack-portal/issues/161: Fix & enable test suite
- [x] https://github.com/blockstack/blockstack-portal/issues/394: resolve issue with underline transition on wallet sidebar on 4 views
- [x] https://github.com/blockstack/blockstack-portal/issues/385: macOS: add storage menu link, update wallet link
- [x] https://github.com/blockstack/blockstack-portal/issues/386: Wallet: production version doesn't load core wallet address
- [x] https://github.com/blockstack/blockstack-portal/issues/391: Round up wallet amount
- [x] https://github.com/blockstack/blockstack-portal/issues/392: Error creating account

#### Pushed to [v0.7.0](https://github.com/blockstack/blockstack-portal/projects/5)
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/214: design launch modal~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/306: capture the user's email when they set up an account~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/320: resolve flexbox flow orientation on home screen~~

#### Backlog
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/296: Move macOS virtualenv core build script to core repo~~
- [ ] ~~https://github.com/blockstack/blockstack-portal/issues/330: integrate a BIP44-compliant HD keychain system~~
