### ISSUE TITLE
Enable Blockstack authentication on the forum

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-portal#276]
This task will be broken down into smaller subtasks:

- [x] Add ES256k support to `ruby-jwt` https://github.com/blockstack/blockstack-portal/issues/310
- [x] Update portal to send username https://github.com/blockstack/blockstack-portal/issues/313
- [x] Create blockstack-ruby library https://github.com/blockstack/blockstack-portal/issues/315
- [x] Create an OmniAuth Blockstack authentication strategy https://github.com/blockstack/blockstack-portal/issues/285
- [x] Create Discourse plugin packaging OmniAuth Blockstack plugin https://github.com/blockstack/blockstack-portal/issues/283
- [x] Resolve forum namespace issues https://github.com/blockstack/blockstack-portal/issues/286

**Notes**
There's an official JWT auth plugin: https://github.com/discourse/discourse-jwt
which depends on: https://github.com/discourse/discourse-omniauth-jwt
and in turn depends on: https://github.com/jwt/ruby-jwt

Algorithms are limited by `ruby-jwt`'s support.  According to `https://forum.blockstack.org/t/why-do-blockstacks-use-of-jwt-diverge-from-standards/445/5?u=larry` we're using an unsupported curve which @shea256 has termed: `ES256K`

**Comment by larrysalibra** [comment]
Added support for ES256X to ruby-jwt: https://github.com/larrysalibra/ruby-jwt/tree/add-secp256k1-support

**Comment by shea256** [comment]
@larrysalibra why don't we split the `ruby-jwt` update into a separate task and then close that one?

**Comment by shea256** [comment]
And we can reference it like we reference #286, #285 and #283 above.

**Comment by larrysalibra** [comment]
@shea256 good idea -> https://github.com/blockstack/blockstack-portal/issues/310

**Comment by larrysalibra** [comment]
<img width="739" alt="screen shot 2017-03-20 at 7 48 58 pm" src="https://cloud.githubusercontent.com/assets/597182/24098947/ecc1a52c-0da7-11e7-90b6-0436db8e90ef.png">
