### ISSUE TITLE
Release overview (v0.6.0)

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-portal#328]
### Highlights

- n/a

#### Tasks
- [ ] https://github.com/blockstack/blockstack-portal/issues/302: design new storage app
- [ ] https://github.com/blockstack/blockstack-portal/issues/322: ui build of storage app design
- [ ] https://github.com/blockstack/blockstack-portal/issues/262: ui build of edit profile pages inside the profiles app
- [ ] https://github.com/blockstack/blockstack-portal/issues/261: design of edit profile pages inside the profiles app
- [ ] https://github.com/blockstack/blockstack-portal/issues/214: design launch modal
- [ ] https://github.com/blockstack/blockstack-portal/issues/242: design the wallet app
- [ ] https://github.com/blockstack/blockstack-portal/issues/258: live design new profiles app 
register pages
- [ ] https://github.com/blockstack/blockstack-portal/issues/259: design live search query view inside profiles app
- [ ] https://github.com/blockstack/blockstack-portal/issues/260: ui build of live search query view inside profiles app
- [ ] https://github.com/blockstack/blockstack-portal/issues/320: resolve flexbox flow orientation on home screen

#### Bugs
n/a

**Comment by guylepage3** [comment]
duplicate to https://github.com/blockstack/blockstack-portal/issues/269
